# Generated by Django 3.1.6 on 2021-02-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210216_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.choice', verbose_name='Перечни'),
            preserve_default=False,
        ),
    ]
