# Generated by Django 3.1.6 on 2021-02-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210216_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Перечень', 'verbose_name_plural': 'Перечни'},
        ),
        migrations.AlterField(
            model_name='choiceid',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос'),
        ),
        migrations.AlterModelTable(
            name='choice',
            table='сhoice',
        ),
    ]
