# Generated by Django 3.1.6 on 2021-02-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210216_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll', verbose_name='Опрос'),
        ),
    ]
