# Generated by Django 3.1.6 on 2021-02-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210217_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='slug',
        ),
    ]
