# Generated by Django 3.1.6 on 2021-02-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20210217_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название'),
        ),
    ]
