# Generated by Django 3.1.6 on 2021-02-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210217_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('Ввод', 'Ввод'), ('Один', 'Один'), ('Много', 'Много')], max_length=32, verbose_name='Тип'),
        ),
    ]
