# Generated by Django 3.1.6 on 2021-02-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210217_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoiceid',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll', verbose_name='Опрос'),
        ),
    ]
